services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules

    command: sleep infinity

    networks:
      - internal_network
      - external_network

  redis:
    restart: unless-stopped
    image: redis:7-alpine
    networks:
      - internal_network
    volumes:s
      - redis-data:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: unless-stopped
    image: postgres:15-alpine
    networks:
      - internal_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: misskey
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

  meilisearch:
    restart: always
    image: kanarikanaru/meilisearch:latest
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=development
    networks:
      - internal_network
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: "curl -s http://localhost:7700/health"
      interval: 5s
      retries: 20

volumes:
  postgres-data:
  redis-data:
  meilisearch-data:
  node_modules:

networks:
  internal_network:
    internal: true
  external_network:
